### ISSUE TITLE
[Question] Why doesn't `_Any` include `nil`?

### ISSUE THREAD

**Issue by adrianthedev** [joeldrapper/literal#102]
In TypeScript, `any` includes `nil`. It kinda looks like it should here as well.

Also, if we can't make `_Any` include `nil` could we get a `_Any_Nil` (can be a different name) type from the library?

**Comment by adrianthedev** [comment]
Now, after reading this, I think a better idea would be to make `_Any` nilable and add an `_Not_nil_Any` type in the library.

**Comment by stevegeek** [comment]
Interesting observation. If Any is considered the top type of the type system in literal then, yeah it should include the nil value (NilClass is a subclass of Object and it's Rubys universal base class)

**Comment by adrianthedev** [comment]
I think I'm not the only one thinking about `_Any` like that.

**Comment by joeldrapper** [comment]
In my mind, “any” is short for any-_THING_ and that does not include _nothing_. We do have `_Void` that will accept anything or nothing.

**Comment by stevegeek** [comment]
Ok on the concept of an Any. But on _Void just being pedantic here but `Void` makes me think more of something like a bottom type, eg `Nothing` in Kotlin (?), or something from which the value is to be considered 'non existent' and not to be used. Maybe there is another name we can consider for what Adrian is looking for (eg Unit?)

**Comment by joeldrapper** [comment]
Yes, `_Void` would normally be used of inconsequential return values. However it does fulfil this role because it always matches. The _Never type is the opposite, which doesn’t match anything or nothing. I’m okay with renaming `_Void` to `_Unit`.

**Comment by adrianthedev** [comment]
Also, if you're pondering this change, this is the stage to make it when it's so early on.

**Comment by adrianthedev** [comment]
Don't say that 😛
I never had to use the keyword "void" in my whole career. Please don't make me do that now.

**Comment by hangsu** [comment]
In case you were looking for more feedback:

I've also been mildly surprised that `_Any` doesn't contain `nil`, and have just now realized `_Void` exists 😅

On intuition, I'd expect `_Any` to include `nil`, and something like `_Exists` to include everything except `nil`

That said, it won't be hard for me to get used to whatever naming you land on.

**Comment by joeldrapper** [comment]
But it’s short for anyTHING. 🤣

**Comment by fractaledmind** [comment]
Not to get too philosophical, but the fact that `nil` is an object kinda makes it a "thing", no?

**Comment by adrianthedev** [comment]
What if it stands for "any type"? Or "any object"?
Any is a standalone word.

**Comment by joeldrapper** [comment]
Depending on your perspective, `nil` is not an object. Yes, it’s technically implemented as an object in Ruby, but it represents the idea of “no object”. I’m open to making `_Any` include `nil`, but what would we name the type that doesn’t include `nil` but does include everything else?

**Comment by adrianthedev** [comment]
We could not have one. 
Or, if you really need on we could use `_NotNil`

**Comment by joeldrapper** [comment]
I think it’s really useful. I guess `_Required` would work.

**Comment by stevegeek** [comment]
Think I'm +1 on the `_Any` includes `nil` , primarily as it seems to be intuitive to me like that too (though I try to avoid using Any most of the time)

Reviewing similar concept in other languages seems to be a mixed bag (eg `Any` vs `Any?` in Kotlin, `AnyRef` in scala can actually be made non-nullable, `std::any` vs `std::optional` in C++ etc) so I guess TypeScript is what influences our intuition here mostly.

Maybe taking a leaf out of Kotlins book, could `_Any?` work?

Disagreements... `nil` doing what it does best 

![](https://i.imgflip.com/92no2l.jpg)

**Comment by joeldrapper** [comment]
`_Any?` is brilliant. Of course, it’s a method name.

**Comment by stevegeek** [comment]
So, if `_Any` is in fact `nil`able, then we should consider an "Any type but not nil (NilClass)" type.

Possible names already suggested or to consider:

- `_NotNilAny`
- `_Anything`
- `_Required`
- `_Any!`
- `_Populated`
- `_NotNil`  or `_NonNil`
- `_NotNilable`  or `_NonNilable`

Any other ideas?
