### ISSUE TITLE
`Literal::Array#*`

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/literal#152]

**Comment by joeldrapper** [comment]
@christopher-b can you comment on this issue so I can assign it to you?

**Comment by christopher-b** [comment]
👌🏻

**Comment by christopher-b** [comment]
Implemented in 32e17e601bf113dd14fd5a311d07248f1aa5063b as part of [this PR](https://github.com/joeldrapper/literal/pull/143).
