### ISSUE TITLE
`Literal::Array#-`

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/literal#153]

**Comment by joeldrapper** [comment]
@christopher-b can you comment on this issue so I can assign it to you?

**Comment by christopher-b** [comment]
👋🏻

**Comment by christopher-b** [comment]
Implemented in ba4988b03a842e5cd9bfe04833677e5c5ea82e63, as part of my [omnibus PR](https://github.com/joeldrapper/literal/pull/143)
