### ISSUE TITLE
`prop :properties` unexpected behaviour

### ISSUE THREAD

**Issue by Vagab** [joeldrapper/literal#234]
if you define `prop :properties, SomeType` it's gonna complain because there's a local variable `properties` defined in the generated initializer. Should it maybe be `__properties`?
Happy to submit a pr if you think that's a good idea

**Comment by joeldrapper** [comment]
Agreed. Can we use `__properties__` for the local to be consistent with other stuff?

**Comment by Vagab** [comment]
made a pr 👍
