### ISSUE TITLE
allow for optional kwargs 

### ISSUE THREAD

**Issue by adrienpoly** [joeldrapper/literal#4]
Thanks for the new Gem it looks very promising 

When working with components I often add a kwargs argument to my component initializer that I pass down to my element builder

```ruby
class Link < Phlex::HTML
  def initialize(href:, **kwargs)
    @href = href
    @kwargs = kwargs
  end

  def template(&)
    a href: @href, **@kwargs, &
  end
end
```

I was wondering if this is something Literal Gem would like to support so that we could dry up our components initializers with attributes while preserving the ability to pass kwargs to component

We could then potentially write our component like that 
```ruby
class Link < Phlex::HTML
  extend Literal::Attributes

  attribute :href, String

  def template(&)
    a href: @href, **@kwargs, &
  end
end
```

not sure if we should magically define kwargs or make it available more explicitly by including another module or adding a new method to the dsl. Maybe also kwargs is not the best name. In JS world, I often used `rest` for that

**Comment by adrienpoly** [comment]
I could get something working like that with the current version

```ruby
class User
  extend Literal::Attributes

  attribute :name, String

  def initialize(**kwargs)
    attributes, @kwargs = kwargs.partition {|k, v| self.class.__attributes__.include?(k)}.map(&:to_h)

    super(**attributes)
  end

  attr_reader :kwargs
end
User.new(name: "John", test: "other attribute")
# => #<User:0x0000000105f33c60 @kwargs={:test=>"other attribute"}, @name="John">

```

**Comment by joeldrapper** [comment]
I like this idea a lot. It would be nice to be able to type check the kwargs as a `_Hash` type.

**Comment by adrienpoly** [comment]
Adding it as a type makes it explicit and that is great, I just feel `_Rest(Symbol, String)` might not be very idiomatic 

Maybe an alternative could be something like 

```ruby
rest_attributes :kwargs
```

**Comment by joeldrapper** [comment]
Yeah, I quite like that and you could pass a type too, e.g.

```ruby
rest_attributes :kwargs, _Hash(Symbol, String)
```

**Comment by Bumppoman** [comment]
I’d like to consider syntax to capture an optional block provided to the initializer too.

**Comment by joeldrapper** [comment]
There should also be syntax to capture positional `*args`. I’m not sure what's the best interface for this.

**Comment by joeldrapper** [comment]
How do people feel about using the attribute names `*`, `**` and `&` as an interface for this, but providing an `as` option that allows you to change the name of the internal attribute?

```ruby
attribute :*, Array, as: :foo 
attribute :**, Hash, as: :bar 
attribute :&, Proc, as: :baz
```

**Comment by joeldrapper** [comment]
Or maybe it could just be a third positional argument.

```ruby
attribute :foo, Array, :*
attribute :bar, Hash, :**
attribute :baz, Proc, :&
```

**Comment by joeldrapper** [comment]
The syntax above is now supported.
