### ISSUE TITLE
Inherited object and kwargs

### ISSUE THREAD

**Issue by adrienpoly** [joeldrapper/literal#57]
Thanks for the solution proposed for supporting kwargs (https://github.com/joeldrapper/literal/issues/4)

I tried it and I am facing an error. It looks like the position of the kwargs attribute is important and this doesn't play well with inheritance.

What I am trying to achieve is to define an ApplicationComponent and within this ApplicationComponent define and `atttributes` attribute for the kwargs

Example

```ruby
class ApplicationComponent < ViewComponent::Base
  extend Literal::Attributes

  attribute :display, _Boolean, default: true
  attribute :attributes, Hash, :**
end
```

This works as expected.
But then I would like my `ButtonComponent` to be defined like that 

```ruby
class ButtonComponent < ApplicationComponent
    attribute :text, String, default: "Hello, world!"

    def call
      content_tag(:button, @text, **@attributes)
    end
  end
```

but I am getting this error
![CleanShot 2023-11-03 at 14 23 32@2x](https://github.com/joeldrapper/literal/assets/7847244/44c050ce-f4ee-4321-a219-f8c4d0aa6298)

**Comment by joeldrapper** [comment]
Hey @adrienpoly, yes, the order of attribute definitions is important at the moment. It needs to follow valid Ruby attribute orderings, which, as you said, makes it difficult to use with inheritance.

It should be possible to sort attributes into the correct order in Literal, but it's going to take quite a complex refactoring to do that.
