### ISSUE TITLE
Starting over

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/literal#79]
Literal is full of so many half-baked experiments. These experiments have taught us a lot about what’s possible. I’m creating a branch called `legacy`, which will be locked to the current state of `main`. If you’re using literal from git in your project, you should point to that branch for the next few months.

After that, I’m going to be ripping everything out and starting again, using the `legacy` branch as reference. This time, I’m only interested in implementing fully tested, documented features. Nothing half-baked.

The initial focus will be on:

- [x] Types
- [x] Unions
- [x] Attributes (now known as Properties)
- [x] Structs
- [x] Data
- [x] Enums

**Comment by joeldrapper** [comment]
Thanks @hangsu! ❤️

`Literal::Decorator` makes sense to include with this. 👍  I want to get this fully documented with 100% code coverage before moving on to other stuff. Some of the other stuff may never make it back in.

**Comment by hangsu** [comment]
> Some of the other stuff may never make it back in.

I like the idea of `literal` being focused on type checking and related conveniences.

If you wanted to expand to monads, memoization, etc. I think a separate gem would make sense. It's easier for me psychologically to buy in to a more focused, cohesive project (like Phlex 😉).
