### ISSUE TITLE
Add `predicate` options to literal properties

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/literal#94]
In the same way you can define readers and writers, it would be nice to have the option to define predicates.

```ruby
prop :happy, _Boolean, predicate: :public
```

Would define the method
```ruby
public def happy?
  @happy
end
```

In the case that the type isn’t `_Boolean`, `true` or `false`, it should define it with a double negation to coerce a truthy/falsy into `true` / `false`.
```ruby
public def happy?
  !!@happy
end
```

**Comment by joelmoss** [comment]
Would be great if boolean props would automatically set `predicate: true`, as I can't imagine you would ever not want that.

**Comment by stevegeek** [comment]
In my implementation of "typed attributes" I also created predicates like this for all attributes. As for the idea of automatically creating them on booleans, but not sure if the asymettry (booleans optional, others not) is confusing, and also does it only apply to predicates for Boolean, or also for Nilable(Boolean) say?
